### ISSUE TITLE
terraform.py using *.tfstate files outside of working directory (and below)

### ISSUE THREAD

**Issue by jmvbxx** [mantl/terraform.py#53]
My current working directory is `~/coding/terraform1` which is where I am trying to run my `ansible-playbook` command using `terraform.py`.

When the command runs it is three other `terraform.tfstate` files that are not in the working directory, or below.

For example:
* `~/coding/project1`
* `~/coding/test`
* etc.

The documentation says that it only reads the state file in the working directory or below. So, am I misreading the documentation or is this undesired behaviour?

Thanks!

**Comment by tlc** [comment]
I'm very curious about this, too!

There's a line causing this that I've commented out in my local copy.

>                                   os.path.abspath(os.path.join(os.path.dirname(__file__),
>                                                                '..', '..', )))

**Comment by jmvbxx** [comment]
I guess we can close this 18 months later ;-)
