### ISSUE TITLE
How to use with Google cloud where tags are lists not maps?

### ISSUE THREAD

**Issue by danielporto** [mantl/terraform.py#84]
How should I annotate my google cloud terraform files?
Tags, different from the examples with azure and aws are lists not maps.
Can you provide a working example for GCP as well?
Thanks!

**Comment by Notifium** [comment]
It's the same with DigitalOcean: https://www.digitalocean.com/community/tutorials/how-to-tag-digitalocean-droplets

**Comment by Cryptophobia** [comment]
Thanks @Notifium !
